#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.msp430.MSP430{1,0,3.3,2
#
suart.x430: package/cfg/suart.x430.mak

clean::
	-$(RM) package/cfg/suart.x430.mak
